services:
  postgres:
    container_name: book_list_db_prod
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booklistdb_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: book_list_backend_prod
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/booklistdb_prod
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: book_list_frontend_prod
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.prod
    ports:
      - "1234:1234"
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:3000
      HOST: "0.0.0.0"
      PORT: 1234
    depends_on:
      - backend

volumes:
  postgres_data:
