FROM node:22.11-alpine AS development

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./
COPY apps/frontend/package*.json ./apps/frontend/

RUN yarn install

COPY . .

EXPOSE 1234

CMD ["yarn", "workspace", "frontend", "dev"]