FROM node:22.11-alpine AS development

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./
COPY apps/backend/package*.json ./apps/backend/

RUN yarn install

COPY . .

RUN yarn workspace backend prisma generate

EXPOSE 3000

CMD ["yarn", "workspace", "backend", "start:dev"]